# Dockerfile.trainer
FROM python:3.10-slim

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ scripts/
RUN python scripts/train_and_download.py
RUN python scripts/evaluate_models.py